import * as fs from 'fs'
import * as path from 'path'
import { Log } from '@quatrain/log'

export class CodeGenerator {
   /**
    * Génère une application complète dans le dossier cible
    */
   public static generate(config: any, targetDir: string): void {
      const fullTargetDir = path.resolve(process.cwd(), targetDir)
      
      // Ensure base directories exist and clear old files to prevent orphans
      const dirs = ['src/models', 'src/api', 'data/migrations/default', 'web/src/pages']
      for (const dir of dirs) {
         const d = path.resolve(fullTargetDir, dir)
         if (!fs.existsSync(d)) {
            fs.mkdirSync(d, { recursive: true })
         } else if (dir === 'src/models' || dir === 'src/api' || dir === 'web/src/pages') {
            fs.readdirSync(d).forEach(file => {
               if (file.endsWith('.ts') || file.endsWith('.tsx')) {
                  fs.unlinkSync(path.join(d, file))
               }
            })
         }
      }

      this.generatePackageJson(config, fullTargetDir)
      this.generateTsConfig(fullTargetDir)
      
      const generatedModels = this.generateModels(config, fullTargetDir)
      this.generateApiEndpoints(config, fullTargetDir, generatedModels)
      this.generateIndex(config, fullTargetDir, generatedModels)
      this.generateMigration(config, fullTargetDir)
      
      this.generateFrontend(config, fullTargetDir, generatedModels)

      Log.info(`[CodeGenerator] Application générée avec succès dans ${fullTargetDir}`)
   }

   private static generateWidgetForm(modelConfig: any, widget: any): string {
      const m = modelConfig.name
      let layoutCode = ''
      
      const properties = modelConfig.properties || []
      const getFieldCode = (fieldName: string) => {
         const prop = properties.find((p:any) => p.name === fieldName)
         let label = fieldName
         if (prop && prop.ui && prop.ui.labels) {
            label = prop.ui.labels.fr || prop.ui.labels.en || fieldName
         }
         return `<TextInput label="${label}" value={data.${fieldName} || ''} onChange={e => setData({...data, ${fieldName}: e.currentTarget.value})} />`
      }

      if (Array.isArray(widget.layout)) {
         widget.layout.forEach((item: any) => {
            if (item.type === 'field' && item.name) {
               layoutCode += `         ${getFieldCode(item.name)}\n`
            } else if (item.type === 'group' && Array.isArray(item.fields)) {
               layoutCode += `         <Group grow align="flex-start">\n`
               item.fields.forEach((f: string) => {
                  layoutCode += `            ${getFieldCode(f)}\n`
               })
               layoutCode += `         </Group>\n`
            }
         })
      }

      return `import { useEffect, useState } from 'react'
import { Group, TextInput, Button, Title, Stack } from '@mantine/core'
import { useNavigate, useParams } from 'react-router-dom'
import { api } from '../api'

export function ${m}Form() {
   const { id } = useParams()
   const navigate = useNavigate()
   const [data, setData] = useState<any>({})

   useEffect(() => {
      if (id && id !== 'new') {
         api.get('${m.toLowerCase()}s/' + id).then(res => {
            if (res && res.data) setData(res.data)
         })
      }
   }, [id])

   const handleSave = async () => {
      try {
         if (id && id !== 'new') {
            await api.patch('${m.toLowerCase()}s/' + id, data)
         } else {
            await api.post('${m.toLowerCase()}s', data)
         }
         navigate('/${m.toLowerCase()}s')
      } catch (e) {
         console.error(e)
         alert("Erreur de sauvegarde")
      }
   }

   return (
      <Stack gap="md" style={{ maxWidth: '800px', margin: '0 auto' }}>
         <Title order={2}>{id === 'new' ? 'Créer' : 'Éditer'} ${m}</Title>
         
         {/* --- Début du layout généré par le WidgetBuilder --- */}
${layoutCode}         {/* --- Fin du layout --- */}
         
         <Group mt="xl">
            <Button onClick={handleSave}>Sauvegarder</Button>
            <Button variant="default" onClick={() => navigate('/${m.toLowerCase()}s')}>Annuler</Button>
         </Group>
      </Stack>
   )
}
`
   }

   private static generatePackageJson(config: any, targetDir: string): void {
      const packagePath = path.resolve(targetDir, 'package.json')
      
      const targetNpmTag = 'latest-dev' // Use 'latest' for production, 'latest-dev' for testing features

      const packageJson = {
         name: config.name?.toLowerCase().replace(/[^a-z0-9]/g, '-') || "quatrain-generated-app",
         version: "1.0.0",
         description: "Generated by Quatrain Studio",
         main: "src/index.ts",
         type: "module",
         scripts: {
            "start:dev": "NODE_ENV=development bun run --watch src/index.ts",
            "start:prod": "NODE_ENV=production bun run src/index.ts"
         },
         dependencies: {
            "@quatrain/core": targetNpmTag,
            "@quatrain/backend": targetNpmTag,
            "@quatrain/backend-sqlite": targetNpmTag,
            "@quatrain/api": targetNpmTag,
            "@quatrain/api-server": targetNpmTag,
            "@quatrain/backend-migrations": targetNpmTag
         } as Record<string, string>
      }

      if (config.authMode === 'oauth') {
         packageJson.dependencies['@quatrain/auth-oidc'] = targetNpmTag
      }
      
      if (config.backend?.adapter === 'PostgresAdapter') {
         packageJson.dependencies['@quatrain/backend-postgres'] = targetNpmTag
      }

      Log.info(`[CodeGenerator] Generating package.json with dependencies`)
      fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2))
   }

   private static generateTsConfig(targetDir: string): void {
      const tsconfig = {
         compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "node",
            esModuleInterop: true,
            strict: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            outDir: "dist"
         },
         include: ["src/**/*", "data/migrations/**/*"]
      }
      fs.writeFileSync(path.resolve(targetDir, 'tsconfig.json'), JSON.stringify(tsconfig, null, 2))
   }

   private static generateModels(config: any, targetDir: string): string[] {
      const models = config.models || []
      const generatedNames: string[] = []

      for (const model of models) {
         if (!model.name) continue
         const className = model.name
         const collectionName = model.collectionName || className.toLowerCase()
         generatedNames.push(className)

         // Helper to map raw types to Property classes
         const mapTypeToClass = (type: string) => {
            if (type.toLowerCase() === 'datetime') return 'DateTimeProperty'
            const formatted = type.charAt(0).toUpperCase() + type.slice(1)
            return formatted.endsWith('Property') ? formatted : formatted + 'Property'
         }

         // Use imports from core properties
         const basePropNames = ['name', 'status', 'createdBy', 'createdAt', 'updatedBy', 'updatedAt']
         const filteredProps = model.properties.filter((p: any) => !basePropNames.includes(p.name))

         const propsCode = filteredProps.map((p: any) => {
            const propClass = mapTypeToClass(p.type)
            const htmlTypeLine = p.htmlType ? `,\n      htmlType: '${p.htmlType}'` : ''
            return `   {
      name: '${p.name}',
      type: ${propClass}.TYPE,
      mandatory: ${p.mandatory ? 'true' : 'false'}${htmlTypeLine}
   }`
         }).join(',\n')

         const coreImports = new Set(filteredProps.map((p: any) => mapTypeToClass(p.type)))
         const propTypesToImport = Array.from(coreImports)
         
         const modelCode = `import { PersistedBaseObject } from '@quatrain/backend'
import { ${propTypesToImport.join(', ')} } from '@quatrain/core'

export const ${className}Properties = [
${propsCode}
]

export class ${className} extends PersistedBaseObject {
   static PROPS_DEFINITION = ${className}Properties
   static COLLECTION = '${collectionName}'

   static async factory(src: any = undefined): Promise<${className}> {
      return super.factory(src, ${className})
   }
}
`
         fs.writeFileSync(path.resolve(targetDir, `src/models/${className}.ts`), modelCode)
      }

      return generatedNames
   }

   private static generateApiEndpoints(config: any, targetDir: string, models: string[]): void {
      for (const className of models) {
         const apiCode = `import { CrudEndpoint, ValuesEndpoint, ListEndpoint } from '@quatrain/api-server'
import { ServerAdapter, EndpointOptions } from '@quatrain/api'
import { ${className} } from '../models/${className}'

export const ${className}Api = (router: ServerAdapter, path: string, options: EndpointOptions) => {
   ValuesEndpoint(${className})(router, path, options)
   ListEndpoint(${className})(router, path, options)
   CrudEndpoint(${className})(router, path, options)
}
`
         fs.writeFileSync(path.resolve(targetDir, `src/api/${className}Api.ts`), apiCode)
      }
   }

   private static generateIndex(config: any, targetDir: string, models: string[]): void {
      const adapterClass = config.backend?.adapter === 'PostgresAdapter' ? 'PostgresAdapter' : 'SQLiteAdapter'
      const adapterImport = config.backend?.adapter === 'PostgresAdapter' ? '@quatrain/backend-postgres' : '@quatrain/backend-sqlite'
      
      const modelImports = models.map(m => `import { ${m} } from './models/${m}'`).join('\n')
      const apiImports = models.map(m => `import { ${m}Api } from './api/${m}Api'`).join('\n')
      const apiRegisters = models.map(m => `      server.addEndpoint(${m}Api, '/api/${m.toLowerCase()}s')`).join('\n')

      const indexCode = `import * as path from 'path'
import { Backend, InjectMetaMiddleware } from '@quatrain/backend'
import { ${adapterClass} } from '${adapterImport}'
import { ExpressAdapter } from '@quatrain/api-server'
import { MigrationManager } from '@quatrain/backend-migrations'
import { Log, DefaultLoggerAdapter, LogLevel } from '@quatrain/log'
${config.authMode === 'oauth' ? `import { AuthOIDC } from '@quatrain/auth-oidc'\n` : ''}
${modelImports}
${apiImports}

;(async () => {
   try {
      const isProd = process.env.NODE_ENV === 'production'
      Log.addLogger('default', new DefaultLoggerAdapter('', isProd ? LogLevel.INFO : LogLevel.DEBUG), true)
      
      const adapter = new ${adapterClass}({ 
         config: ${adapterClass === 'SQLiteAdapter' ? '{ database: path.resolve(process.cwd(), "data/app.sqlite") }' : 'process.env.DATABASE_URL'},
         middlewares: [new InjectMetaMiddleware()]
      })

      Backend.addBackend(adapter, 'default', true)
      
      const mm = new MigrationManager(adapter)
      await mm.executeMigrations()
      
      const server = new ExpressAdapter()
      
${apiRegisters}

${config.authMode === 'oauth' ? `      // Initialize OIDC Auth
      const oidc = AuthOIDC.init('http://localhost:4001')
      server.getNativeInstance().use('/oidc', oidc.callback())
` : ''}

      const PORT = Number(process.env.PORT) || 4001
      server.start(PORT, () => {
         console.log(\`🚀 Server started on port \${PORT}\`)
      })
   } catch (e) {
      console.error(e)
      process.exit(1)
   }
})()
`
      fs.writeFileSync(path.resolve(targetDir, 'src/index.ts'), indexCode)
   }

   private static generateMigration(config: any, targetDir: string): void {
      const models = config.models || []
      
      let upQueries = ''
      let downQueries = ''

      for (const model of models) {
         if (!model.name) continue
         const collectionName = model.collectionName || model.name.toLowerCase()
         
         const baseColumns = ['id', 'name', 'status', 'createdby', 'createdat', 'updatedby', 'updatedat', 'deletedby', 'deletedat']
         
         const customColumns = model.properties
            .filter((p: any) => !baseColumns.includes(p.name.toLowerCase()))
            .map((p: any) => {
               // Very simplified SQLite type mapping for the PoC
               let sqlType = 'TEXT'
               if (p.type === 'NumberProperty' || p.type === 'BooleanProperty') sqlType = 'INTEGER'
               return `${p.name.toLowerCase()} ${sqlType}`
            })

         const allColumns = [
            'id TEXT PRIMARY KEY',
            'name TEXT',
            'status TEXT',
            'createdat INTEGER',
            'updatedat INTEGER',
            'deletedat INTEGER',
            'createdby TEXT',
            'updatedby TEXT',
            'deletedby TEXT',
            ...customColumns
         ].join(',\n            ')

         let alterQueries = ''
         customColumns.forEach((colDef: string) => {
            alterQueries += `
      try {
         await adapter.rawQuery(\`ALTER TABLE ${collectionName} ADD COLUMN ${colDef}\`)
      } catch (e) {
         // Ignore error if column already exists
      }\n`
         })

         upQueries += `
      await adapter.rawQuery(\`CREATE TABLE IF NOT EXISTS ${collectionName} (
            ${allColumns}
      )\`)\n${alterQueries}`

         downQueries += `
      await adapter.rawQuery('DROP TABLE IF EXISTS ${collectionName}')\n`
      }

      const migrationCode = `import { AbstractBackendAdapter } from '@quatrain/backend'

export const up = async ({ context: adapter }: { context: AbstractBackendAdapter }) => {
   try {${upQueries}
   } catch (e) {
      console.error('Migration up error', e)
   }
}

export const down = async ({ context: adapter }: { context: AbstractBackendAdapter }) => {
   try {${downQueries}
   } catch (e) {
      console.error('Migration down error', e)
   }
}
`
      const migrationsDir = path.resolve(targetDir, 'data/migrations/default')
      // Clear old migrations to prevent executing buggy or duplicate past generations
      if (fs.existsSync(migrationsDir)) {
         fs.readdirSync(migrationsDir).forEach(file => {
            if (file.endsWith('.ts')) {
               fs.unlinkSync(path.join(migrationsDir, file))
            }
         })
      }

      const timestamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14)
      fs.writeFileSync(path.join(migrationsDir, `${timestamp}_init.ts`), migrationCode)
   }

   private static generateFrontend(config: any, targetDir: string, models: string[]): void {
      const appName = config.name?.toLowerCase().replace(/[^a-z0-9]/g, '-') || "quatrain-app"
      const webDir = path.resolve(targetDir, 'web')
      if (!fs.existsSync(webDir)) {
         fs.mkdirSync(webDir, { recursive: true })
      }
      const srcDir = path.resolve(webDir, 'src')
      if (!fs.existsSync(srcDir)) {
         fs.mkdirSync(srcDir, { recursive: true })
      }
      const pagesDir = path.resolve(srcDir, 'pages')
      if (!fs.existsSync(pagesDir)) {
         fs.mkdirSync(pagesDir, { recursive: true })
      }

      // package.json
      const packageJson = {
         name: "quatrain-ui-front",
         private: true,
         version: "1.0.0",
         type: "module",
         scripts: {
            "dev": "vite",
            "build": "tsc && vite build",
            "preview": "vite preview"
         },
         dependencies: {
            "@mantine/core": "^7.11.1",
            "@mantine/hooks": "^7.11.1",
            "@quatrain/api-client": "latest-dev",
            "@quatrain/ui-form-react": "latest-dev",
            "react": "^18.3.1",
            "react-dom": "^18.3.1",
            "react-router-dom": "^6.24.1"
         },
         devDependencies: {
            "@types/react": "^18.3.3",
            "@types/react-dom": "^18.3.0",
            "@vitejs/plugin-react": "^4.3.1",
            "typescript": "^5.5.3",
            "vite": "^5.3.4"
         }
      }
      fs.writeFileSync(path.join(webDir, 'package.json'), JSON.stringify(packageJson, null, 2))

      // tsconfig.json
      const tsConfig = {
         compilerOptions: {
            target: "ES2020",
            useDefineForClassFields: true,
            lib: ["ES2020", "DOM", "DOM.Iterable"],
            module: "ESNext",
            skipLibCheck: true,
            moduleResolution: "bundler",
            allowImportingTsExtensions: true,
            resolveJsonModule: true,
            isolatedModules: true,
            noEmit: true,
            jsx: "react-jsx",
            strict: true,
            noUnusedLocals: true,
            noUnusedParameters: true,
            noFallthroughCasesInSwitch: true,
            types: ["vite/client"]
         },
         include: ["src"]
      }
      fs.writeFileSync(path.join(webDir, 'tsconfig.json'), JSON.stringify(tsConfig, null, 2))

      // vite.config.ts
      const viteConfig = `import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  return {
    plugins: [react()],
    server: {
      host: '0.0.0.0',
      port: 3000,
      proxy: {
        '/api': {
          target: 'http://localhost:4001',
          changeOrigin: true
        }
      }
    }
  }
})
`
      fs.writeFileSync(path.join(webDir, 'vite.config.ts'), viteConfig)

      // .env
      const envContent = `VITE_API_URL=/api
`
      fs.writeFileSync(path.join(webDir, '.env'), envContent)

      // index.html
      const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Quatrain App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
      fs.writeFileSync(path.join(webDir, 'index.html'), indexHtml)

      // main.tsx
      const mainTsx = `import React from 'react'
import ReactDOM from 'react-dom/client'
import { MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'
import { BrowserRouter } from 'react-router-dom'
import App from './App.tsx'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <MantineProvider defaultColorScheme="dark">
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </MantineProvider>
  </React.StrictMode>,
)
`
      fs.writeFileSync(path.join(srcDir, 'main.tsx'), mainTsx)

      // api.ts
      const apiTs = `import { ApiClient } from '@quatrain/api-client'

const apiUrl = import.meta.env.VITE_API_URL || '/api'
export const api = new ApiClient(apiUrl)
`
      fs.writeFileSync(path.join(srcDir, 'api.ts'), apiTs)

      // App.tsx
      const menuItems = models.map(m => 
         `          <a href="/${m.toLowerCase()}s" style={{display: 'block', padding: '10px', color: 'white', textDecoration: 'none'}}>${m}s</a>`
      ).join('\n')

      const routes = models.map(m => 
         `            <Route path="/${m.toLowerCase()}s" element={<${m}List />} />\n            <Route path="/${m.toLowerCase()}s/:id" element={<${m}Form />} />`
      ).join('\n')

      const imports = models.map(m => 
         `import { ${m}List } from './pages/${m}List'\nimport { ${m}Form } from './pages/${m}Form'`
      ).join('\n')

      const appTsx = `import { AppShell, Burger, Group, Title } from '@mantine/core'
import { useDisclosure } from '@mantine/hooks'
import { Routes, Route } from 'react-router-dom'
${imports}

export default function App() {
  const [opened, { toggle }] = useDisclosure()

  return (
    <AppShell
      header={{ height: 60 }}
      navbar={{
        width: 300,
        breakpoint: 'sm',
        collapsed: { mobile: !opened },
      }}
      padding="md"
    >
      <AppShell.Header>
        <Group h="100%" px="md">
          <Burger opened={opened} onClick={toggle} hiddenFrom="sm" size="sm" />
          <Title order={3}>Quatrain App</Title>
        </Group>
      </AppShell.Header>

      <AppShell.Navbar p="md">
${menuItems}
      </AppShell.Navbar>

      <AppShell.Main>
         <Routes>
${routes}
            <Route path="/" element={<div>Welcome to your Quatrain Application</div>} />
         </Routes>
      </AppShell.Main>
    </AppShell>
  )
}
`
      fs.writeFileSync(path.join(srcDir, 'App.tsx'), appTsx)

      // Generate CRUD pages
      for (const m of models) {
         const modelConfig = config.models.find((mod: any) => mod.name === m)
         const props = modelConfig?.properties || []

         const listTsx = `import { useEffect, useState } from 'react'
import { Table, Button, Group, Title } from '@mantine/core'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'

export function ${m}List() {
   const [data, setData] = useState<any[]>([])
   const navigate = useNavigate()

   useEffect(() => {
      api.get('${m.toLowerCase()}s').then((res) => {
         if (res && res.data) {
            setData(res.data)
         }
      })
   }, [])

   const handleDelete = async (id: string) => {
      if (confirm('Are you sure?')) {
         await api.delete('${m.toLowerCase()}s/' + id, {})
         setData(data.filter(item => item.uid !== id))
      }
   }

   return (
      <div>
         <Group justify="space-between" mb="md">
            <Title order={2}>${m}s</Title>
            <Button onClick={() => navigate('/${m.toLowerCase()}s/new')}>Create ${m}</Button>
         </Group>
         <Table>
            <Table.Thead>
               <Table.Tr>
                  <Table.Th>Name</Table.Th>
                  <Table.Th>Status</Table.Th>
                  <Table.Th>Actions</Table.Th>
               </Table.Tr>
            </Table.Thead>
            <Table.Tbody>
               {data.map(item => (
                  <Table.Tr key={item.uid}>
                     <Table.Td>{item.name || item.uid}</Table.Td>
                     <Table.Td>{item.status}</Table.Td>
                     <Table.Td>
                        <Group>
                           <Button size="xs" variant="outline" onClick={() => navigate(\`/${m.toLowerCase()}s/\${item.uid}\`)}>Edit</Button>
                           <Button size="xs" color="red" variant="outline" onClick={() => handleDelete(item.uid)}>Delete</Button>
                        </Group>
                     </Table.Td>
                  </Table.Tr>
               ))}
            </Table.Tbody>
         </Table>
      </div>
   )
}
`
         fs.writeFileSync(path.join(pagesDir, `${m}List.tsx`), listTsx)

         const modelSchemaStr = JSON.stringify(modelConfig, null, 3)

         let formTsx = ''
         const widgets = config.widgets || []
         const formWidget = widgets.find((w: any) => w.modelName === m && w.widgetType === 'form')

         if (formWidget && Array.isArray(formWidget.layout) && formWidget.layout.length > 0) {
            // Utilisation du générateur natif de composants !
            formTsx = this.generateWidgetForm(modelConfig, formWidget)
         } else {
            // Fallback historique sur CoreForm dynamique
            formTsx = `import { CoreForm } from '@quatrain/ui-form-react'
import { useNavigate, useParams } from 'react-router-dom'
import { api } from '../api'

export function ${m}Form() {
   const { id } = useParams()
   const navigate = useNavigate()

   const modelSchema = ${modelSchemaStr}

   return (
      <CoreForm 
         modelSchema={modelSchema} 
         objectId={id} 
         apiClient={api} 
         onSave={() => navigate('/${m.toLowerCase()}s')}
         onCancel={() => navigate('/${m.toLowerCase()}s')}
      />
   )
}
`
         }
         fs.writeFileSync(path.join(pagesDir, `${m}Form.tsx`), formTsx)
      }

      // Dockerfile
      const dockerfile = `FROM node:22-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`
      fs.writeFileSync(path.join(webDir, 'Dockerfile'), dockerfile)

      // nginx.conf
      const nginxConf = `server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://engine:4001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
`
      fs.writeFileSync(path.join(webDir, 'nginx.conf'), nginxConf)
   }
}
