"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GoneError = exports.NotFoundError = exports.ForbiddenError = exports.UnauthorizedError = exports.BadRequestError = exports.EntityRepository = exports.Entity = exports.UserRepository = exports.User = exports.InjectKeywordsMiddleware = exports.InjectMetaMiddleware = exports.SortAndLimit = exports.Sorting = exports.Limits = exports.Filters = exports.Filter = exports.Query = exports.BackendError = exports.BaseRepository = exports.BackendAction = exports.AuthenticationError = exports.AbstractAuthAdapter = exports.AuthAction = exports.BaseObjectProperties = exports.BaseObjectCore = exports.AbstractObject = exports.DataObject = exports.ObjectUri = exports.MockAdapter = exports.AbstractAdapter = exports.StringProperty = exports.ObjectProperty = exports.HashProperty = exports.EnumProperty = exports.DateTimeProperty = exports.BooleanProperty = exports.BaseProperty = exports.Property = exports.Core = exports.utils = exports.statuses = void 0;
const Core_1 = require("./Core");
Object.defineProperty(exports, "Core", { enumerable: true, get: function () { return Core_1.Core; } });
const statuses = __importStar(require("./common/statuses"));
exports.statuses = statuses;
const utils = __importStar(require("./utils"));
exports.utils = utils;
const Property_1 = require("./properties/Property");
Object.defineProperty(exports, "Property", { enumerable: true, get: function () { return Property_1.Property; } });
const BaseProperty_1 = require("./properties/BaseProperty");
Object.defineProperty(exports, "BaseProperty", { enumerable: true, get: function () { return BaseProperty_1.BaseProperty; } });
const StringProperty_1 = require("./properties/StringProperty");
Object.defineProperty(exports, "StringProperty", { enumerable: true, get: function () { return StringProperty_1.StringProperty; } });
const EnumProperty_1 = require("./properties/EnumProperty");
Object.defineProperty(exports, "EnumProperty", { enumerable: true, get: function () { return EnumProperty_1.EnumProperty; } });
const BooleanProperty_1 = require("./properties/BooleanProperty");
Object.defineProperty(exports, "BooleanProperty", { enumerable: true, get: function () { return BooleanProperty_1.BooleanProperty; } });
const ObjectProperty_1 = require("./properties/ObjectProperty");
Object.defineProperty(exports, "ObjectProperty", { enumerable: true, get: function () { return ObjectProperty_1.ObjectProperty; } });
const DateTimeProperty_1 = require("./properties/DateTimeProperty");
Object.defineProperty(exports, "DateTimeProperty", { enumerable: true, get: function () { return DateTimeProperty_1.DateTimeProperty; } });
const HashProperty_1 = require("./properties/HashProperty");
Object.defineProperty(exports, "HashProperty", { enumerable: true, get: function () { return HashProperty_1.HashProperty; } });
const AbstractObject_1 = require("./components/AbstractObject");
Object.defineProperty(exports, "AbstractObject", { enumerable: true, get: function () { return AbstractObject_1.AbstractObject; } });
const ObjectUri_1 = require("./components/ObjectUri");
Object.defineProperty(exports, "ObjectUri", { enumerable: true, get: function () { return ObjectUri_1.ObjectUri; } });
const DataObject_1 = require("./components/DataObject");
Object.defineProperty(exports, "DataObject", { enumerable: true, get: function () { return DataObject_1.DataObject; } });
const BaseObjectCore_1 = require("./components/BaseObjectCore");
Object.defineProperty(exports, "BaseObjectCore", { enumerable: true, get: function () { return BaseObjectCore_1.BaseObjectCore; } });
const BaseObject_1 = require("./components/BaseObject");
Object.defineProperty(exports, "BaseObjectProperties", { enumerable: true, get: function () { return BaseObject_1.BaseObjectProperties; } });
const InjectMetaMiddleware_1 = require("./backends/middlewares/InjectMetaMiddleware");
Object.defineProperty(exports, "InjectMetaMiddleware", { enumerable: true, get: function () { return InjectMetaMiddleware_1.InjectMetaMiddleware; } });
const InjectKeywordsMiddleware_1 = require("./backends/middlewares/InjectKeywordsMiddleware");
Object.defineProperty(exports, "InjectKeywordsMiddleware", { enumerable: true, get: function () { return InjectKeywordsMiddleware_1.InjectKeywordsMiddleware; } });
const BaseRepository_1 = __importDefault(require("./components/BaseRepository"));
exports.BaseRepository = BaseRepository_1.default;
const Backend_1 = require("./Backend");
Object.defineProperty(exports, "BackendAction", { enumerable: true, get: function () { return Backend_1.BackendAction; } });
const User_1 = require("./components/User");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return User_1.User; } });
const UserRepository_1 = __importDefault(require("./components/UserRepository"));
exports.UserRepository = UserRepository_1.default;
const Entity_1 = require("./components/Entity");
Object.defineProperty(exports, "Entity", { enumerable: true, get: function () { return Entity_1.Entity; } });
const EntityRepository_1 = __importDefault(require("./components/EntityRepository"));
exports.EntityRepository = EntityRepository_1.default;
const Auth_1 = require("./Auth");
Object.defineProperty(exports, "AuthAction", { enumerable: true, get: function () { return Auth_1.AuthAction; } });
const authentication_1 = require("./authentication");
Object.defineProperty(exports, "AbstractAuthAdapter", { enumerable: true, get: function () { return authentication_1.AbstractAuthAdapter; } });
Object.defineProperty(exports, "AuthenticationError", { enumerable: true, get: function () { return authentication_1.AuthenticationError; } });
const backends_1 = require("./backends");
Object.defineProperty(exports, "AbstractAdapter", { enumerable: true, get: function () { return backends_1.AbstractAdapter; } });
Object.defineProperty(exports, "MockAdapter", { enumerable: true, get: function () { return backends_1.MockAdapter; } });
Object.defineProperty(exports, "BackendError", { enumerable: true, get: function () { return backends_1.BackendError; } });
Object.defineProperty(exports, "Query", { enumerable: true, get: function () { return backends_1.Query; } });
Object.defineProperty(exports, "Filter", { enumerable: true, get: function () { return backends_1.Filter; } });
Object.defineProperty(exports, "Filters", { enumerable: true, get: function () { return backends_1.Filters; } });
Object.defineProperty(exports, "Limits", { enumerable: true, get: function () { return backends_1.Limits; } });
Object.defineProperty(exports, "Sorting", { enumerable: true, get: function () { return backends_1.Sorting; } });
Object.defineProperty(exports, "SortAndLimit", { enumerable: true, get: function () { return backends_1.SortAndLimit; } });
const ResourcesErrors_1 = require("./common/ResourcesErrors");
Object.defineProperty(exports, "BadRequestError", { enumerable: true, get: function () { return ResourcesErrors_1.BadRequestError; } });
Object.defineProperty(exports, "UnauthorizedError", { enumerable: true, get: function () { return ResourcesErrors_1.UnauthorizedError; } });
Object.defineProperty(exports, "ForbiddenError", { enumerable: true, get: function () { return ResourcesErrors_1.ForbiddenError; } });
Object.defineProperty(exports, "NotFoundError", { enumerable: true, get: function () { return ResourcesErrors_1.NotFoundError; } });
Object.defineProperty(exports, "GoneError", { enumerable: true, get: function () { return ResourcesErrors_1.GoneError; } });
