services:
  engine:
    build:
      context: .
      dockerfile: Containerfile
    restart: unless-stopped
    ports:
      - 4001:4001
    environment:
      NODE_ENV: production
    networks:
      - env-development-net
    volumes:
      - ./quatrain.json:/app/quatrain.json:ro
      - ./data:/app/data
  ui:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:80
    networks:
      - env-development-net
    depends_on:
      - engine
networks:
  env-development-net:
    driver: bridge
