"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UNKNOWN = exports.MAINTENANCE = exports.DONE = exports.DISABLED = exports.DELETED = exports.DELETABLE = exports.SUSPENDED = exports.TEST = exports.ERROR = exports.COMPLETED = exports.ACTIVE = exports.QUEUED = exports.PENDING = exports.CREATED = void 0;
exports.CREATED = 'created';
exports.PENDING = 'pending';
exports.QUEUED = 'queued';
exports.ACTIVE = 'active';
exports.COMPLETED = 'completed';
exports.ERROR = 'error';
exports.TEST = 'test';
exports.SUSPENDED = 'suspended';
exports.DELETABLE = 'deletable';
exports.DELETED = 'deleted';
exports.DISABLED = 'disabled';
exports.DONE = 'done';
exports.MAINTENANCE = 'maintenance';
exports.UNKNOWN = 'unknown';
