name: Publish Documentation to GitHub Pages

on:
  push:
    branches:
      - main



concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # NOSONAR

      - name: Setup Node
        uses: actions/setup-node@v4 # NOSONAR
        with:
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Pages
        uses: actions/configure-pages@v4 # NOSONAR

      - name: Install dependencies
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install

      - name: Build packages
        run: yarn node bin/publish_all.js --build-only

      - name: Build documentation
        run: yarn typedoc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # NOSONAR
        with:
          path: './docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # NOSONAR
