name: Publish Studio-Image Container

on:
  push:
    branches:
      - main
    paths:
      - 'containers/studio-image/**'
      - 'apps/studio-api/**'
      - 'apps/studio-web/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/studio-image

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # NOSONAR

      - name: Get version from package.json
        id: package-version
        run: echo "VERSION=$(jq -r .version containers/studio-image/package.json)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3 # NOSONAR
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5 # NOSONAR
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # NOSONAR
        with:
          context: .
          file: containers/studio-image/ContainerFile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Bump package version
        run: |
          npm --no-git-tag-version --prefix containers/studio-image version patch

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v5 # NOSONAR
        with:
          commit_message: "chore(studio-image): bump patch version [skip ci]"
          file_pattern: "containers/studio-image/package.json"
